### PR TITLE
feat/fix: Add `forceUpdateElement` utility method and resolve reload crash

### LINKED ISSUE #291: Fix crash on reload
When reloading discord (ctrl+r), the console indicates that Discord crashed (`AppCrashedFatalReport lastCrash: `) with an object including the current date). I believe this is also why you're brought back to the friends view after reloading. We need to figure out how to properly handle a reload. Maybe there's something we need to stop to allow it to successfully exit?

### LINKED ISSUE #315: Add `forceUpdateElement` to utils
You can take the code from my Mention Cache Fix plugin:
https://github.com/asportnoy/mention-cache-fix/blob/69592d0d9c94b6675660cf48a5caaf928363306d/src/index.ts#L81-L92

Just needs some doc comments

### PR DESCRIPTION
**Pull request by GriefMoDz**
### Proposed Changes:
- Add `forceUpdateElement` utility method (closes #315)
    - I've added `@types/react-reconciler` as a dependency to make use of an actual type for `Fiber`. 
- Resolve crash on reload (closes #291)
    - Enforcing `bypassCSP` on a registered privileged scheme is the cause of this.

### CODE REVIEW

File: src/main/index.ts [hunk 1]
```diff
@@ -93,7 +96,7 @@ electron.protocol.registerSchemesAsPrivileged([
   {
     scheme: "replugged",
     privileges: {
-      bypassCSP: true,
+      // bypassCSP: true,
```
Comment (asportnoy) [inline src/main/index.ts:99]:
```suggestion
```

**Review by asportnoy — APPROVED** [review]
Can confirm fix works. Nice find!
