### PR TITLE
fix "Load Missing Plugins" not reloading plugin list

### LINKED ISSUE #79: Plugin detected by "Load Missing Plugins" doesn't show up until reloading menu
**Describe the bug**
If you add a plugin to the folder and reload your plugins in-place with "Load Missing Plugins", it will show that it located the plugin but it will not appear in the list until you exit the menu and reopen it.

**Expected behavior**
The plugin should appear in the list without reload.

**Desktop (please complete the following information):**
 - OS: Linux
 - Replugged version: a1af079

**Additional context**
 - [ X ] I checked if Discord and/or Replugged are up to date
 - [ X ] I made sure this is not related to an external plugin or a theme

### PR DESCRIPTION
**Pull request by thennothinghappened**
Fixes #79

### CODE REVIEW

File: src/Powercord/plugins/pc-moduleManager/components/manage/Plugins.jsx [hunk 1]
```diff
@@ -28,9 +28,10 @@ class Plugins extends Base {
     return this._sortItems(plugins);
   }
 
-  fetchMissing () { // @todo: better impl + i18n
+  async fetchMissing () { // @todo: better impl + i18n
     // noinspection JSIgnoredPromiseFromCall
```
Comment (asportnoy) [inline src/Powercord/plugins/pc-moduleManager/components/manage/Plugins.jsx:32]:
```suggestion
```

File: src/Powercord/plugins/pc-moduleManager/components/manage/Plugins.jsx [hunk 2]
```diff
@@ -28,9 +28,10 @@ class Plugins extends Base {
     return this._sortItems(plugins);
   }
 
-  fetchMissing () { // @todo: better impl + i18n
+  async fetchMissing () { // @todo: better impl + i18n
```
Comment (asportnoy) [inline src/Powercord/plugins/pc-moduleManager/components/manage/Plugins.jsx:31]:
```suggestion
  async fetchMissing () {
```

**Review by asportnoy — CHANGES_REQUESTED** [review]
Neither of these are applicable anymore so should be removed

**Review by asportnoy — APPROVED** [review]
